#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.refractored.samples.progressfragment.Resource", IsApplication=true)]

namespace com.refractored.samples.progressfragment
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.compontents.progressfragment.Resource.Id.content_container = global::com.refractored.samples.progressfragment.Resource.Id.content_container;
			global::com.refractored.compontents.progressfragment.Resource.Id.grid = global::com.refractored.samples.progressfragment.Resource.Id.grid;
			global::com.refractored.compontents.progressfragment.Resource.Id.grid_container = global::com.refractored.samples.progressfragment.Resource.Id.grid_container;
			global::com.refractored.compontents.progressfragment.Resource.Id.progress_container = global::com.refractored.samples.progressfragment.Resource.Id.progress_container;
			global::com.refractored.compontents.progressfragment.Resource.Id.progress_text = global::com.refractored.samples.progressfragment.Resource.Id.progress_text;
			global::com.refractored.compontents.progressfragment.Resource.Layout.fragment_grid = global::com.refractored.samples.progressfragment.Resource.Layout.fragment_grid;
			global::com.refractored.compontents.progressfragment.Resource.Layout.fragment_progress = global::com.refractored.samples.progressfragment.Resource.Layout.fragment_progress;
			global::com.refractored.compontents.progressfragment.Resource.String.ApplicationName = global::com.refractored.samples.progressfragment.Resource.String.ApplicationName;
			global::com.refractored.compontents.progressfragment.Resource.String.Hello = global::com.refractored.samples.progressfragment.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int emo_im_crying = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int seattle = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int content_container = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int grid = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int grid_container = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int menu_refresh = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int progress_container = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int progress_text = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_custom_progress = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_grid = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_progress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int view_content = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int refresh = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int description = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int empty = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int loading = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int menu_refresh = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
